### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by panktishah26** [tinkerbell/cluster-api-provider-tinkerbell#178]
We have kubified all the Tinkerbell services like Tink-apis, Hegel, Boots, Rufio, etc.. We have accommodated changes related to those services in CAPT. Thus, we should cut a new release for that.

**Comment by thebsdbox** [comment]
100% agree.

**Comment by displague** [comment]
- tink 0.7.0 (https://github.com/tinkerbell/tink/issues/634)
- hegel 0.7.0 (released)
- boots 0.7.0 (released)
- rufio 0.1.0 (released)
- docs should have an initial versioned release (while all "main" branches are immediately released today, it would be helpful to have point-in-time comparisons to measure Sandbox 0.6.0 (and related ecosystem) experience vs Docs 0.6.0 expectations). Some projects offer a version drop-down in the docs site allowing users to review documentation for previous releases.

Others?

**Comment by chrisdoherty4** [comment]
@displague FWIW this won't use 0.7 of Rufio as it has breaking changes compare with what CAPT was integrated with. There's a ticket to update Rufio for the 0.3 release.

**Comment by jacobweinstock** [comment]
FYI, for Rufio folks will need to build off of Rufio commit: 4dc2085adc8e

**Comment by displague** [comment]
Moving a [slack conversation with @chrisdoherty4](https://cloud-native.slack.com/archives/C01SRB41GMT/p1661354282588489) here:

> With this comment were you suggesting we update everything in CAPT to versions before the release?
> My plan was to update everything for the 0.3 which will be a fast follow. This would be in an effort to ensure stability given CAPT works as is.

What is the goal of v0.2 vs v0.3? Will v0.2 represent the current head or will it be applied to a previous commit?  There are significant changes in v0.2 if we tag from head (https://github.com/tinkerbell/cluster-api-provider-tinkerbell/releases/edit/untagged-fa5686deb4d4f9a21237).

What is the expected diff between v0.3 and v0.2 (since you plan a fast-follow)?

Why release v0.3 separately? 

(Not questioning this flow, just looking to understand so we can consider and provide user guidance)

**Comment by chrisdoherty4** [comment]
0.2 is just to stamp a known working version of CAPT. 0.3 updates CAPT to work with released versions of everything.

We could tag 0.2 as earlier but I'm not sure what commit to tag from and it feels unnecessary given the major change was around Rufio integration which we won't declare support for yet given it was unreleased when initially integrated and has since changed in Rufio 0.1.

Does this sound sensible? If you can point to a commit that you know works and is better than head we could consider it.

**Comment by chrisdoherty4** [comment]
Consider 0.2 a snapshot of something functional with the corresponding dependencies in go.mod. 0.3 is a snapshot against versioned artifacts with updated APIs etc.
